### PR TITLE
fix test address not right

### LINKED ISSUE #461: TestWsNotify
The use of these two places is inconsistent. Inside is map (https://github.com/Qitmeer/qitmeer/blob/0.10-dev/testutils/testwallet.go#L78), but outside is array (https://github.com/Qitmeer/qitmeer/blob/0.10-dev/testutils/ws_test.go#L50)
error message:
https://travis-ci.com/github/Qitmeer/qitmeer/builds/222050277#L726

### PR DESCRIPTION
**Pull request by jamesvan2019**
Fix #461

### CODE REVIEW

**Review by dindinw — APPROVED** [review]

File: testutils/ws_test.go [hunk 1]
```diff
@@ -44,10 +44,10 @@ func TestWsNotify(t *testing.T) {
 		return
 	}
 	spendAmt := types.Amount{Value: 50 * types.AtomsPerCoin, Id: types.MEERID}
-	txid := Spend(t, h, spendAmt)
+	txid, addr := Spend(t, h, spendAmt)
 	t.Logf("[%v]: tx %v which spend %v has been sent", h.Node.Id(), txid, spendAmt.String())
 	t.Log(h.Wallet.Addresses())
-	AssertMempoolTxNotify(t, h, txid.String(), h.Wallet.Addresses()[1], 5)
+	AssertMempoolTxNotify(t, h, txid.String(), addr.String(), 5)
```
Comment (dindinw) [inline testutils/ws_test.go:50]: should not the spend keep in  the order of addresses? 
if ```addr != wallet.addresses[1]```, does not mean some kind of double there?

**Review by lochjin — APPROVED** [review]
